export class Compras{
    IdCompra: number
    Folio: number
    PO: string
    IdProveedor: number
    Proveedor: string
    Subtotal: string
    Total: string
    Descuento: string
    ImpuestosRetenidos: string
    ImpuestosTrasladados: string
    Moneda: string
    Observaciones: string
    TipoCambio: string
    CondicionesPago: string
    SacosTotales: string
    PesoTotal: string
    Estatus: string
    Factura: number
    Ver: string
    FechaElaboracion: Date
    FechaPromesa: Date
    FechaEntrega: Date
    Comprador: string
    SubtotalDlls: string
    TotalDlls: string
    DescuentoDlls: string
    ImpuestosTrasladadosDlls: string 
}